### ISSUE TITLE
Remove asyncawait library (browser compatibility)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-testing#37]
The ``asyncawait`` library was introduced [here](https://github.com/ethereumjs/ethereumjs-testing/commit/f19f34b7d488ac0dc0960dec5aeaca4215a678c4), dated from October 2017 and with the goal to support Node 6.

This is causing browser compatibility problems in the VM and potentially other libraries, see https://github.com/ethereumjs/ethereumjs-vm/issues/465.

Since we have now dropped Node 6 https://github.com/ethereumjs/organization/pull/50 this PR can be reverted.

This should be followed by a new release (also updating the tests).

**Comment by whymarrh** [comment]
@holgerd77 I'll take this

**Comment by holgerd77** [comment]
Cool!
